# Generated by Django 2.2 on 2020-11-10 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_orgs', to='orgs.User'),
            preserve_default=False,
        ),
    ]
