# Generated by Django 2.2 on 2020-11-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_org_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='location',
            field=models.CharField(default='Sears tower', max_length=255),
            preserve_default=False,
        ),
    ]
